name: Create DevOps Change Request in ServiceNow

# Controls when the workflow will run
on:
  # Triggers the workflow on branch creation
  create

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Log the new branch name
        run: echo "Branch \"${{ github.ref_name }}\" was just created."
