name: Create DevOps Change Request in ServiceNow

# Controls when the workflow will run
on:
  # Triggers the workflow on branch creation
  create
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create:
    name: Create a ServiceNow Change Request
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # sw-ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - name: Get Ticket Number
        id: get_ticket_num ## if [[ "$branch_name" =~ (HR[C]?|INC|RITM|SCTASK)\d+ ]]
        run: |
          branch_name=${{ github.ref_name }}
          ticket_num=$(echo "$branch_name" | sed -nE "(HR[C]?|INC|RITM|SCTASK)\d+")
          echo "Extracted ticket_num is $ticket_num"

      - name: Prepare Message
        id: prepare_msg
        run: |
          echo "MESSAGE<<EOF" >> $GITHUB_ENV
          echo "GitHub branch has been created." >> $GITHUB_ENV
          echo "\tRepository: ${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "\tBranch name: ${{ github.ref_name }}" >> $GITHUB_ENV
          echo "\tTriggered by: ${{ github.actor }}" >> $GITHUB_ENV
          echo "\tTicket number: "

      - name: Test
        run: echo "TEST \ $MESSAGE"

      # - name: Create
      #   # For custom action based change, remove or disable the 'deployment-gate' configuration and the 'deploy' step. Ensure to update to the latest version of the custom action, for e.g. ServiceNow/servicenow-devops-change@v5.1.0
      #   uses: ServiceNow/servicenow-devops-change@v6.1.0
      #   with:
      #     # Devops Integration Token
      #     devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
      #     # ServiceNow Instance URL
      #     instance-url: ${{ secrets.SN_INSTANCE_URL }}
      #     # Orchestration Tool Id
      #     tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
      #     # GitHub Context
      #     context-github: ${{ toJSON(github) }}
      #     # Display Name of the Job
      #     job-name: Create a ServiceNow Change Request
      #     # change-request: snDevOpsChange
      #     # Unsupported fields are: risk, impact, and risk_impact_analysis
      #     change-request: '{
      #       "short_description": ${{ github.ref_name }},
      #       "description": "Automatically created by GitHub Action in response to a new branch being created. TODO: Associate branch to service or something",
      #       "work_notes": 
      #         "GitHub Branch Created.\n"
      #       }'
      #     change-request: '{"attributes":{"priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes","start_date": "2023-09-07 11:59:59","end_date": "2023-09-09 11:59:59"}}'
      #     # You can specify the requested_by attribute either with name or sys_id. Example: "requested_by":{"name": "Test User"} or "requested_by": "62826bf03710200044e0bfc8bcbe5df1"
      #     # You can specify the assignment_group attribute either with name or sys_id. Example: "assignment_group":{"name": "Change Approval Team"} or "assignment_group": "5f721d93c0a8010e015533746de18bf9"
      #     # start_date: This is the planned start date
      #     # end_date: This is the planned end date
      #     # For deployment gate based change, uncomment the 'deployment-gate' configuration and the 'deploy' step 
      #     # deployment-gate: '{"environment": "deploy-gates-demo", "jobName": "Deploy"}'